spring.datasource.url=jdbc:postgresql://localhost:5432/weblab4
spring.datasource.username=client
spring.datasource.password=pass54321
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ???????? ??????? ??????????????
spring.security.user.name=admin
spring.security.user.password=admin

cors.allowed-origins=http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173
